### ISSUE TITLE
Zip file is corrupted

### ISSUE THREAD

**Issue by buraketmen** [clowee/The-Technical-Debt-Dataset#3]
Hi,
I get an error when I want to extract the file. I think the DB file inside the ZIP file is malformed. 
I wonder if you can upload the file again.
Thanks.

**Comment by davidetaibi** [comment]
It seems that the zip file cannot be properly unzipped with Windows. 

Please, unzip with Mac or linux, or download the compressed file from https://drive.google.com/file/d/1zNrUjyfz3UBhpNsHG1mjpZVzwNRUdpUW/view?usp=sharing

**Comment by davidetaibi** [comment]
Fixed re-uploading the new version
