### ISSUE TITLE
Source code availability

### ISSUE THREAD

**Issue by rmahdav** [clowee/The-Technical-Debt-Dataset#5]
Hi,

When I download the zip file of the source code from [here](https://github.com/clowee/The-Technical-Debt-Dataset/releases/tag/1.0), I can see just one ReadMe file. I appreciate it if you take a look at it. I am interested in the source code of the data retrieval pipeline.

Thanks!

**Comment by bakhtos** [comment]
Hello,

Indeed, the source code published in the release automatically is just the archive of this repo, which only contains the readme file (on the "master" branch).
You may explore the other branch of the repo, "2.0", which seems to contain some instructions and scripts for an old pipeline (used before my time with the team) of some previous versions.

I was creating the 2.0 version of the dataset, and there was no pipeline as such - simply shell scripts iteratively calling tools (SZZ, RefactoringMiner etc) on each of the cloned projects in the folder. Outputs were processed and input in the .db file manually.
