### ISSUE TITLE
Dataset Replication

### ISSUE THREAD

**Issue by marodev** [clowee/The-Technical-Debt-Dataset#6]
Hi @nyyti and @davidetaibi,

I was trying to replicate the dataset and encountered the following issues:

1. There are no CSV files available (as mentioned in the paper)
2. I wonder how to join SONAR_MEASURES and SONAR_ISSUES as the composite foreign key seems to be missing in SONAR_ISSUES but the figure shows a relation? For example, I want all SONAR_ISSUES that were reported on a specific SQAnalysisDate (table SONAR_MEASURES).

![image](https://user-images.githubusercontent.com/23633010/113830269-bf8c8000-9786-11eb-9764-e6c5317f6bab.png)

Thanks!

**Comment by davidetaibi** [comment]
Hello Martin, 
unfortunately we discovered a bug in the CSV files. At the moment the dataset is published mainly as sqlite database, but if you need the csv, you can just "export" each table from sqlite studio (or any other sqlite browser). 

The table sonar_issue can be joined with the table sonar_measures using the closeCommitHash or openCommitHash. 

Each Analysis might open or close some issues, therefore, if you want to know all the issues introduced in a specific analysis, you need to join SONAR_MEASURES.commitHash with SONARW_ISSUES.creationCommitHash. 

BTW, we are releasing the new version of the dataset, with some improvements on the analysis. 
This version has some issues in three projects, where we analyzed by mistake some commits on different branches. The V2 will include only the analysis of the commits in the main branch. 

Do not esitate to contact us if you need help, also in the tools settings, or in any other part of your work.
