### ISSUE TITLE
REFACTORING_MINER - Strange numbers

### ISSUE THREAD

**Issue by TahLoow** [clowee/The-Technical-Debt-Dataset#7]
Hello,

For part of my research I reconstructed a lot of the data presented in the TDD. I ran RefactoringMiner 1.0, 2.0, and 2.1 all on the main branch of Ambari, Accumulo, Beam, and Zookeeper. I've been getting significantly different numbers from yours. Obviously this could be an error of my own implementation. The numbers just strike me as odd, and I haven't found an explanation otherwise, so I thought I would give you a heads up. 

The below results are from Refactoring Miner 2.1. I tried with Refactoring Miner 1.0 and 2.0 as well and still got significantly different results. 

| Project | TDD 1.01 | TDD 2.0 | Ours |
| ------- | -------- | ------- | ---- |
| Ambari  | 342 | Removed | 43,921 |
| Accumulo | 368 | Removed | 72,600 |
| Beam | 10,105 | Removed | 82,493 |
| Zookeeper | 2,077 | 2,077 | 7,836 |

Lastly, I had a total of 43,921 refactorings from just those four projects. Comparatively, TDD 2.0 had 37,226 refactorings across 31 projects. 

If you know why there is this discrepancy, please reach out. The TDD has been a wonderful resource. 
Kind regards

**Comment by bakhtos** [comment]
Hello,

The 2.0 release was published in stages, and Refacroting miner data was the last to be added.
At the time you cloned the dataset, it actually contained the data from the 1.0 version, unchanged.
I have now finalised the 2.0 version and published a new release, feel free to explore it and sorry for the confusion about the data.
